version: '3.9'
services:
  stripe-node:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4242:4242"
    volumes:
      - .:/usr/src/app
    environment:
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
    #command: "tail -f /dev/null"