version: '3.9'
services:
  stripe-node:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4242:4242"
    volumes:
      - .:/usr/src/app
    environment:
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - CREATE_CUSTOMER_URL=${CREATE_CUSTOMER_URL}
      - EVENT_NAME=${EVENT_NAME}
      - EVENT_PHASE=${EVENT_PHASE}
      - TICKET_NAME=${TICKET_NAME}
      - TICKET_PRICE_ID=${TICKET_PRICE_ID}
      - DOMAIN=${DOMAIN}
      - RETURN_URL=${RETURN_URL}
      - FOLDER_NODE=${FOLDER_NODE}
      - PORT=${PORT}

    #command: "tail -f /dev/null"
    networks:
      - emms24_emmsnetwork
    restart: always
networks:
  emms24_emmsnetwork:
    external: true
